// Run before committing: node migration/build-assets.mjs
// Wrangler runs --check: a deploy must include the archive of every hash it serves.
import { readdir, readFile, writeFile, mkdir, rm, cp } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { gzipSync, gunzipSync } from 'node:zlib';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(process.env.BOTC_BUILD_ROOT || fileURLToPath(new URL('../', import.meta.url)));
const check = process.argv.includes('--check');
const read = p => readFile(resolve(root, p), 'utf8');
const hash = bytes => createHash('sha256').update(bytes).digest('hex').slice(0, 20);
const archivePath = 'migration/asset-archive.json';
let archive = {};
try { archive = JSON.parse(await read(archivePath)); } catch (error) { if (error.code !== 'ENOENT') throw error; }
const assets = {}, current = {};
for (const file of (await readdir(resolve(root, 'assets'))).sort()) {
  if (!/\.(js|css)$/.test(file)) continue;
  let body = await read('assets/' + file);
  // CSS moves one directory down; keep relative fonts/textures pointed at assets/.
  if (file.endsWith('.css')) body = body.replace(/url\(\s*(['"]?)([^)'"\s]+)\1\s*\)/g, (all, quote, url) =>
    /^(?:[a-z]+:|\/|#)/i.test(url) ? all : 'url(' + quote + '../' + url + quote + ')');
  const name = file.replace(/\.(js|css)$/, '.' + hash(body) + '.$1');
  assets[file] = 'immutable/' + name;
  current[name] = body;
  if (archive[name]) {
    if (gunzipSync(Buffer.from(archive[name], 'base64')).toString() !== body) throw new Error('Immutable asset collision: ' + name);
  } else {
    if (check) throw new Error('Run node migration/build-assets.mjs and commit its generated files before deploying: ' + file);
    archive[name] = gzipSync(body, { level: 9 }).toString('base64');
  }
}
const sources = [];
for (const directory of ['', 'worker']) {
  for (const file of (await readdir(resolve(root, directory))).sort()) {
    if (!/\.(html|js)$/.test(file) || file === 'asset-manifest.js') continue;
    const path = directory ? directory + '/' + file : file;
    sources.push(path + '\n' + await read(path));
  }
}
// A deployment stamp also rolls SSR when only the Worker or HTML changes.
const buildId = hash(JSON.stringify(assets) + sources.join('\n'));
const manifest = '// Generated by migration/build-assets.mjs; do not edit.\n' +
  'export const BUILD_ID = ' + JSON.stringify(buildId) + ';\n' +
  'export default ' + JSON.stringify(assets, null, 2) + ';\n';
if (check) {
  if (await read('worker/asset-manifest.js') !== manifest) throw new Error('Asset manifest is stale. Run node migration/build-assets.mjs before committing.');
} else {
  await writeFile(resolve(root, 'worker/asset-manifest.js'), manifest);
  await writeFile(resolve(root, archivePath), JSON.stringify(archive, null, 2) + '\n');
}
const out = resolve(root, '.build/public');
await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });
// Explicit public inputs; Worker source, tests and archives never get uploaded.
await cp(resolve(root, 'assets'), resolve(out, 'assets'), { recursive: true });
// These three historical character addresses are still public redirect stubs.
await cp(resolve(root, 'characters'), resolve(out, 'characters'), { recursive: true });
await mkdir(resolve(out, 'assets/immutable'), { recursive: true });
for (const [name, compressed] of Object.entries(archive)) {
  if (!/^[a-z0-9._-]+\.[a-f0-9]{20}\.(js|css)$/i.test(name)) throw new Error('Invalid archive path');
  await writeFile(resolve(out, 'assets/immutable', name), gunzipSync(Buffer.from(compressed, 'base64')));
}
function replacePaths(text) {
  return text.replace(/assets\/([a-z0-9._-]+\.(?:js|css))\b/gi, (all, file) => assets[file] ? 'assets/' + assets[file] : all);
}
const bootstrap = '<script>window.BOTC_ASSETS=' + JSON.stringify(assets) + ';</script>';
for (const file of await readdir(root)) {
  if (!/\.(html|json|txt|xml|ico|png|webmanifest)$/.test(file) && !['_headers', '_redirects'].includes(file)) continue;
  const body = await readFile(resolve(root, file));
  let output = body;
  // Keep the encoding declaration within the first 1024 bytes. The manifest
  // is larger than that and must follow it, before any inline consumers.
  if (/\.html$/.test(file)) output = replacePaths(body.toString()).replace(/<meta\s+charset=[^>]+>/i, '$&\n' + bootstrap);
  if (file === '_headers') output = replacePaths(body.toString());
  await writeFile(resolve(out, file), output);
}
console.log('Built ' + Object.keys(assets).length + ' versioned assets; retained ' + Object.keys(archive).length + ' immutable files. Build ' + buildId);
